apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-replace-values
  labels:
    {{- include "github-scaffolding-with-composition-page.labels" . | nindent 4 }}
data:
  values: |
    { "organizationName": "{{ .Values.git.toRepo.org }}",
      "repositoryName": "{{ .Values.git.toRepo.name }}",
      "serviceType": "{{ .Values.app.service.type }}",
      "servicePort": "{{ .Values.app.service.port }}"
    }
