apiVersion: git.krateo.io/v1alpha1
kind: Repo
metadata:
  name: {{ .Release.Name }}-repo
  labels:
    {{- include "github-scaffolding.labels" . | nindent 4 }}
  annotations:
    krateo.io/paused: "{{ default false (and .Values.global .Values.global.gracefullyPaused) }}"
spec:
  unsupportedCapabilities: {{ .Values.git.unsupportedCapabilities }}
  insecure: {{ .Values.git.insecure }}
  configMapKeyRef:
    namespace: {{ .Release.Namespace }}
    name: {{ .Release.Name }}-replace-values
    key: values
  fromRepo:
    url: {{ include "github-scaffolding.fromRepoUrl" . }}
    branch: {{ .Values.git.fromRepo.branch }}
    authMethod: {{ .Values.git.fromRepo.credentials.authMethod }}
    path: {{ .Values.git.fromRepo.path }}
    secretRef:
      namespace: {{ .Values.git.fromRepo.credentials.secretRef.namespace }}
      name: {{ .Values.git.fromRepo.credentials.secretRef.name }}
      key: {{ .Values.git.fromRepo.credentials.secretRef.key }}
  toRepo:
    url: {{ include "github-scaffolding.toRepoUrl" . }}
    branch: {{ .Values.git.toRepo.branch }}
    authMethod: {{ .Values.git.toRepo.credentials.authMethod }}
    path: {{ .Values.git.toRepo.path }}
    secretRef:
      namespace: {{ .Values.git.toRepo.credentials.secretRef.namespace }}
      name: {{ .Values.git.toRepo.credentials.secretRef.name }}
      key: {{ .Values.git.toRepo.credentials.secretRef.key }}