apiVersion: github.kog.krateo.io/v1alpha1
kind: Repo
metadata:
  name: {{ .Release.Name }}-repo
  labels:
    {{- include "github-scaffolding-with-composition-page.labels" . | nindent 4 }}
  annotations:
    krateo.io/connector-verbose: "{{ .Values.git.toRepo.verbose }}"
    krateo.io/deletion-policy: {{ .Values.git.toRepo.deletionPolicy | lower }}
    krateo.io/paused: "{{ default false (and .Values.global .Values.global.gracefullyPaused) }}"
spec:
  authenticationRefs:
    bearerAuthRef: bearer-github-ref
  org: {{ .Values.git.toRepo.org }}
  name: {{ .Values.git.toRepo.name }}
  private: {{ .Values.git.toRepo.private }}
  auto_init: {{ .Values.git.toRepo.initialize }}
